import { useMemo, useState } from "react";
import { useApp } from "../app/context";
import { buildHash, useRoute } from "../app/router";
import { printAs } from "../app/print";
import { AssessabilityBadge, ExposureBadge, Pill, SeverityBadge } from "../components/Badge";
import { Chips } from "../components/KeyValue";
import { Section } from "../components/Section";
import { STATUS_LABEL, STATUS_ORDER, areaSummaries, controlsByAgent, fixFirst, packetTotals, type AreaSummary, type Status } from "../data/evidence";
import { changes } from "../data/drift";
import { agentLabel, dimensionMatrix, formatDate, pluralize } from "../data/selectors";

type View = "officer" | "underwriter";

export function Evidence() {
  const { envelope, framework } = useApp();
  const route = useRoute();
  const view: View = route.query.get("view") === "underwriter" ? "underwriter" : "officer";
  const [copied, setCopied] = useState<"idle" | "done" | "manual">("idle");

  const json = useMemo(() => JSON.stringify(envelope.registry, null, 2), [envelope.registry]);
  const copyJson = async () => {
    try {
      await navigator.clipboard.writeText(json);
      setCopied("done");
    } catch {
      setCopied("manual");
    }
  };
  const downloadHref = useMemo(() => `data:application/json;charset=utf-8,${encodeURIComponent(json)}`, [json]);

  return (
    <div>
      <div className="flex flex-wrap items-baseline justify-between gap-2 no-pack">
        <h1 className="text-[24px] m-0">Evidence</h1>
        <div className="flex flex-wrap items-center gap-2 no-print">
          <div role="tablist" aria-label="View" className="flex items-center gap-2">
            {(["officer", "underwriter"] as const).map((v) => (
              <a key={v} role="tab" aria-selected={view === v} href={buildHash("evidence", null, v === "officer" ? {} : { view: v })} className={`rounded border px-3 py-1 text-[13px] no-underline ${view === v ? "border-navy bg-navy text-white" : "border-line bg-panel text-ink"}`}>
                {v === "officer" ? "Risk officer view" : "Underwriter view"}
              </a>
            ))}
          </div>
          <span className="w-px h-5 bg-line mx-1" aria-hidden="true" />
          <button type="button" onClick={() => printAs("summary")} className="rounded border border-line bg-panel px-3 py-1 text-[13px] hover:bg-paper">Print summary</button>
          <button type="button" onClick={() => printAs("pack")} className="rounded border border-navy bg-navy text-white px-3 py-1 text-[13px] hover:bg-navy-700">Print evidence pack</button>
          <a href={downloadHref} download="stoa-registry.json" className="rounded border border-line bg-panel px-3 py-1 text-[13px] no-underline text-ink hover:bg-paper">Download report JSON</a>
          <button type="button" onClick={copyJson} className="rounded border border-line bg-panel px-3 py-1 text-[13px] hover:bg-paper">{copied === "done" ? "Copied" : "Copy JSON"}</button>
        </div>
      </div>
      <p className="caption mt-1 mb-0 no-pack">{view === "officer" ? "Remediation-oriented: what is wrong, who owns it, how to fix it." : "Exposure-oriented: what the agents can do, which controls were observed or declared, contradictions, drift, and confidence per dimension."}{copied === "manual" ? " Clipboard access was blocked in this viewer; use Download or select the JSON manually." : ""}</p>

      <div className="screen-view">{view === "officer" ? <OfficerView /> : <UnderwriterView />}</div>
      <div className="print-pack">
        <PackHeader />
        <UnderwriterView />
      </div>
      <p className="caption mt-6 no-pack">Framework labels ({framework === "owasp" ? "OWASP LLM Top 10 (2025)" : framework === "eu" ? "EU AI Act" : "NIST AI RMF"}) never change a score. Stoa prepares evidence; carriers price and issue.</p>
    </div>
  );
}

function PackHeader() {
  const { envelope } = useApp();
  const r = envelope.registry;
  const head = r.repository.head_commit;
  return (
    <header className="border-b border-line pb-2 mb-4">
      <div className="font-serif text-[20px] text-navy">{r.repository.name} · AI agent evidence pack</div>
      <div className="caption">{r.repository.git_ref ?? "no git ref"}{head ? ` · committed ${formatDate(head.date)}` : ""} · {r.summary.files_scanned} files scanned · generated by Stoa {envelope.generator.version} · registry schema {r.schema_version}</div>
    </header>
  );
}

function OfficerView() {
  const { envelope } = useApp();
  const fixes = fixFirst(envelope);
  const register = envelope.register;
  const owners = new Map<string, number>();
  for (const a of envelope.registry.agents) {
    const o = a.declared?.owner;
    if (o) owners.set(o, (owners.get(o) ?? 0) + 1);
  }
  return (
    <div>
      <Section title="What is wrong" caption="Critical and high findings merged by rule and fix, worst first. Each item is the shortest path that clears its findings.">
        {fixes.length === 0 ? <p className="caption m-0">No critical or high findings in this scan.</p> : (
          <ol className="m-0 p-0 list-none panel divide-y divide-line">
            {fixes.map((f, i) => (
              <li key={`${f.rule_id}-${i}`} className="p-3 grid gap-x-4 gap-y-1 md:grid-cols-[28px_1fr_1fr] text-[13px]">
                <span className="font-serif text-gold text-[20px] leading-none tabular-nums">{i + 1}</span>
                <div>
                  <div className="flex items-center gap-2 flex-wrap"><SeverityBadge severity={f.severity} /><span className="mono">{f.rule_id}</span><span className="font-medium">{f.title}</span><span className="caption">{pluralize(f.refs.length, "finding")}</span></div>
                  <p className="m-0 mt-1">{f.soWhat}</p>
                  <ul className="m-0 mt-1 p-0 list-none caption mono">
                    {f.refs.slice(0, 4).map((r) => <li key={r.finding.fingerprint}><a href={buildHash("findings", r.finding.fingerprint)} className="link">{r.finding.path}:{r.finding.line}</a>{r.agent ? ` · ${agentLabel(r.agent)}` : ""}</li>)}
                    {f.refs.length > 4 ? <li>and {f.refs.length - 4} more</li> : null}
                  </ul>
                </div>
                <div>
                  <div className="caption uppercase text-[11px] tracking-wide">How to fix</div>
                  <p className="m-0">{f.remediation}</p>
                  <div className="caption mt-1">{f.owners.length ? `Owner: ${f.owners.join(", ")}` : "Owner: not declared"}</div>
                </div>
              </li>
            ))}
          </ol>
        )}
      </Section>

      <Section title="Who owns it" caption="Declared owners from stoa-declared.toml and the register's treatments.">
        <div className="grid gap-4 md:grid-cols-2">
          <div className="panel p-3">
            <div className="caption uppercase text-[11px] tracking-wide mb-2">Agent owners</div>
            {owners.size === 0 ? <p className="caption m-0">No agent has a declared owner.</p> : (
              <ul className="m-0 p-0 list-none flex flex-col gap-1 text-[13px]">
                {[...owners.entries()].sort((a, b) => b[1] - a[1]).map(([o, n]) => <li key={o} className="flex justify-between gap-2 min-w-0"><span className="break-all">{o}</span><span className="caption tabular-nums whitespace-nowrap">{pluralize(n, "agent")}</span></li>)}
              </ul>
            )}
            <p className="caption mt-2 mb-0">{envelope.registry.agents.filter((a) => !a.declared?.owner).length} agents have no declared owner.</p>
          </div>
          <div className="panel p-3">
            <div className="caption uppercase text-[11px] tracking-wide mb-2">Register treatments</div>
            {register.length === 0 ? <p className="caption m-0">The register is empty.</p> : (
              <ul className="m-0 p-0 list-none flex flex-col gap-1 text-[13px]">
                {register.map((row) => (
                  <li key={row.risk_id} className="flex items-center justify-between gap-2">
                    <a href={buildHash("register", row.risk_id)} className="link truncate">{row.dimension_name} · {row.agent_name ?? row.agent_id}</a>
                    <span className="flex items-center gap-2 whitespace-nowrap">{row.residual ? <ExposureBadge exposure={row.residual.level} /> : null}{row.declared?.treatment ? <Pill tone={row.declared.treatment === "transfer" ? "gold" : "neutral"}>{row.declared.treatment}</Pill> : <span className="caption">undeclared</span>}</span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </Section>
    </div>
  );
}

function UnderwriterView() {
  const { envelope, framework } = useApp();
  const r = envelope.registry;
  const highImpact = new Set(envelope.vocabulary.high_impact_capabilities);
  const sensitive = new Set(envelope.vocabulary.sensitive_integrations);
  const controls = controlsByAgent(envelope);
  const areas = areaSummaries(envelope.assurance);
  const totals = packetTotals(areas);
  const groups = dimensionMatrix(envelope, framework);
  const drift = changes(envelope);
  const review = drift.filter((c) => c.needsReview);
  const uw = envelope.underwriting;
  const contradictions = envelope.assurance.contradictions;

  return (
    <div>
      <Section title="What the agents can do" caption="Capabilities and integrations observed in code, declared limits, and autonomy declared versus inferred.">
        <div className="panel overflow-x-auto">
          <table className="tbl">
            <thead><tr><th>Agent</th><th>Capabilities</th><th>Integrations</th><th>Autonomy declared / inferred</th><th>Max per action</th><th>Worst exposure</th></tr></thead>
            <tbody>
              {r.agents.map((a) => {
                const c = controls.find((x) => x.agentId === a.id);
                const worst = (a.dimension_assessment?.dimensions ?? []).reduce<string>((w, d) => (d.exposure === "elevated" ? "elevated" : w === "elevated" ? w : d.exposure === "moderate" ? "moderate" : w), "none-observed");
                const mismatch = Boolean(c?.declaredAutonomy && c?.inferredAutonomy && c.declaredAutonomy !== c.inferredAutonomy);
                return (
                  <tr key={a.id}>
                    <td className="font-medium">{agentLabel(a)}<div className="caption mono">{a.path}</div></td>
                    <td><Chips items={a.capabilities.map((x) => ({ label: x, hot: highImpact.has(x) }))} empty="none observed" /></td>
                    <td><Chips items={a.integrations.map((x) => ({ label: x, hot: sensitive.has(x) }))} empty="none observed" /></td>
                    <td className={mismatch ? "text-sev-high font-medium" : ""}>{c?.declaredAutonomy ?? "not declared"} / {c?.inferredAutonomy ?? "indeterminate"}</td>
                    <td>{c?.maxPerAction ?? <span className="caption">not declared</span>}</td>
                    <td><ExposureBadge exposure={worst as "elevated" | "moderate" | "none-observed"} /></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </Section>

      <Section title="Controls: observed versus declared" caption="Observed means the scanner saw the control in code or infrastructure; declared means a human wrote it in stoa-declared.toml. Neither is a claim the control works.">
        <div className="panel overflow-x-auto">
          <table className="tbl">
            <thead><tr><th>Agent</th><th>Controls observed in code</th></tr></thead>
            <tbody>
              {controls.map((c) => (
                <tr key={c.agentId}><td>{c.name}</td><td><Chips items={c.observed.map((x) => ({ label: x }))} empty="none observed" /></td></tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-3 panel p-3">
          <div className="flex flex-wrap gap-3 text-[13px]">
            {STATUS_ORDER.map((st) => <span key={st} className="flex items-center gap-1.5"><StatusDot status={st} />{STATUS_LABEL[st]} <span className="tabular-nums caption">{totals[st]}</span></span>)}
          </div>
          <p className="caption mt-2 mb-0">Assurance packet {envelope.assurance.schema}: every row of the 18 areas carries exactly one status. Not provided is listed, never omitted.</p>
        </div>
        <div className="mt-3 grid gap-2 md:grid-cols-2">
          {areas.map((a) => <AreaCard key={a.key} area={a} />)}
        </div>
      </Section>

      <Section title="Contradictions" caption="Where declarations do not match the code. This is what a self-attested questionnaire cannot catch.">
        {contradictions.length === 0 ? <p className="caption m-0">No declared-versus-scanned contradictions in this scan.</p> : (
          <ul className="m-0 p-0 list-none panel divide-y divide-line text-[13px]">
            {contradictions.map((c, i) => (
              <li key={i} className="p-3 flex flex-wrap items-center gap-2">
                {typeof c.severity === "string" ? <SeverityBadge severity={c.severity as "critical" | "high" | "medium" | "low" | "info"} /> : null}
                <span className="mono">{String(c.rule_id ?? "")}</span>
                <span>{String(c.title ?? c.message ?? "")}</span>
                {typeof c.agent === "string" ? <span className="caption">{c.agent}</span> : null}
                {typeof c.path === "string" ? <span className="caption mono">{c.path}{typeof c.line === "number" ? `:${c.line}` : ""}</span> : null}
              </li>
            ))}
          </ul>
        )}
      </Section>

      <Section title="Drift since last assessment" caption={envelope.diff ? `Against ${envelope.baseline?.git_ref ?? envelope.diff.base.commit ?? "baseline"}${envelope.baseline?.head_commit ? ` (${formatDate(envelope.baseline.head_commit.date)})` : ""}.` : "No baseline in this scan."}>
        {!envelope.diff ? <p className="caption m-0">Provide a baseline (stoa scan --diff-against, or stoa dashboard --baseline) to show what changed.</p> : (
          <div className="text-[13px]">
            <p className="m-0">{pluralize(envelope.diff.summary.agents_changed, "agent")} changed, {envelope.diff.summary.agents_added} added, {envelope.diff.summary.agents_removed} removed. {envelope.diff.summary.escalations.high} high-impact escalations. Unapproved max drift <strong>{envelope.diff.summary.unapproved_max_drift_severity}</strong>.</p>
            {review.length ? (
              <ul className="m-0 mt-2 p-0 list-none panel divide-y divide-line">
                {review.map((c, i) => <li key={i} className="p-2 flex flex-wrap items-center gap-2"><span className="font-medium">{c.agentName}</span><span className="caption">{c.kind.replace(/_/g, " ")}</span><span className="mono">{c.label}</span><span className="caption">{c.detail}</span><Pill tone="warn">needs review</Pill></li>)}
              </ul>
            ) : <p className="caption mt-1 mb-0">No unapproved authority increases.</p>}
          </div>
        )}
      </Section>

      <Section title="Confidence per dimension" caption="How directly static analysis observes each dimension. Proxy dimensions are capped at moderate by design.">
        <div className="panel overflow-x-auto">
          <table className="tbl">
            <thead><tr><th>Category</th><th>Dimension</th><th>Confidence</th><th>Organization-wide exposure</th><th>Agents elevated / moderate</th></tr></thead>
            <tbody>
              {groups.flatMap((g) => g.cells.map((c, i) => (
                <tr key={c.dimension.id}>
                  <td className="caption">{i === 0 ? `${g.id} · ${g.label}` : ""}</td>
                  <td>{c.dimension.name}<div className="caption">{c.dimension.definition}</div></td>
                  <td><AssessabilityBadge assessability={c.dimension.assessability} /></td>
                  <td><ExposureBadge exposure={c.maxExposure} /></td>
                  <td className="tabular-nums">{c.agentsElevated} / {c.agentsModerate}</td>
                </tr>
              )))}
            </tbody>
          </table>
        </div>
      </Section>

      <Section title="Questionnaire inputs" caption="What the scan can pre-fill in an AI model risk questionnaire. Identity and measured performance figures come from the applicant, never from a scan.">
        <div className="panel p-3 grid gap-2 md:grid-cols-2 text-[13px]">
          <Row k="Agent candidates" v={String(uw.agent_count)} />
          <Row k="Critical findings" v={String(uw.critical_count)} />
          <Row k="Injection and output-handling evidence" v={uw.robustness ? "findings present (AI001 / AI002)" : "none observed"} />
          <Row k="Scan in CI with drift gating" v={uw.code_quality ? "available through stoa diff" : "not available"} />
          <Row k="Observability" v={uw.monitoring ? "no CTRL004 gap observed" : "CTRL004 gap observed"} />
          <Row k="Declarations present" v={uw.has_declarations ? "yes" : "no"} />
          <Row k="Economic-authority findings" v={uw.econ_findings.length ? uw.econ_findings.join(", ") : "none"} />
          <Row k="Elevated dimensions" v={uw.elevated_dims.length ? uw.elevated_dims.join(", ") : "none"} />
        </div>
      </Section>
    </div>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return <div className="flex justify-between gap-3 border-b border-line/60 py-1"><span className="caption">{k}</span><span className="text-right">{v}</span></div>;
}

function StatusDot({ status }: { status: Status }) {
  const cls: Record<Status, string> = { scanned: "bg-ok", declared: "bg-sev-info", ingested: "bg-navy", observed: "bg-gold", not_provided: "bg-line" };
  return <span aria-hidden="true" className={`inline-block w-2.5 h-2.5 rounded-full ${cls[status]}`} />;
}

function AreaCard({ area }: { area: AreaSummary }) {
  const [open, setOpen] = useState(false);
  const total = STATUS_ORDER.reduce((n, st) => n + area.counts[st], 0);
  return (
    <div className="panel p-3 text-[13px]">
      <button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="w-full text-left flex items-start justify-between gap-2">
        <span><span className="caption">{area.group} · </span><span className="font-medium">{area.name}</span><span className="caption"> · {area.layers}</span></span>
        <span className="flex gap-2 whitespace-nowrap">{STATUS_ORDER.filter((st) => area.counts[st]).map((st) => <span key={st} className="flex items-center gap-1 caption"><StatusDot status={st} />{area.counts[st]}</span>)}{total === 0 ? <span className="caption">no rows</span> : null}</span>
      </button>
      {open && area.rows.length ? (
        <ul className="m-0 mt-2 p-0 list-none flex flex-col gap-0.5 caption">
          {area.rows.map((row, i) => <li key={i} className="flex items-center gap-2"><StatusDot status={row.status} /><span className="mono">{row.field}</span>{row.agent ? <span>{row.agent}</span> : null}<span>{STATUS_LABEL[row.status]}</span></li>)}
        </ul>
      ) : null}
    </div>
  );
}
