import { useApp } from "../app/context";
import { ExposureBadge, SeverityBadge } from "./Badge";
import { RISK_LABEL, RISK_LEVELS, agentLabel, countByLevel, activeFindings, dimensionMatrix, elevatedAgents, formatDate, stats, topRisks } from "../data/selectors";
import { fixFirst } from "../data/evidence";

/**
 * The one-page summary. Hidden on screen; shown by the "summary" print mode
 * from any screen. Deliberately dense and text-first so it fits one page.
 */
export function PrintSummary() {
  const { envelope, framework } = useApp();
  const r = envelope.registry;
  const s = stats(envelope);
  const groups = dimensionMatrix(envelope, framework);
  const elevated = elevatedAgents(envelope);
  const risks = topRisks(envelope, 5);
  const fixes = fixFirst(envelope).slice(0, 5);
  const head = r.repository.head_commit;
  const levels = countByLevel(activeFindings(r));
  const activeTotal = RISK_LEVELS.reduce((n, l) => n + levels[l], 0);

  return (
    <section className="print-summary" aria-hidden="true">
      <header className="flex items-baseline justify-between border-b border-line pb-2 mb-3">
        <div>
          <div className="text-[17px] font-semibold text-navy">{r.repository.name} · AI agent risk summary</div>
          <div className="caption">{r.repository.git_ref ?? "no git ref"}{head ? ` · committed ${formatDate(head.date)}` : ""} · {r.summary.files_scanned} files scanned · generated by Stoa {envelope.generator.version}</div>
        </div>
        <div className="text-[14px] font-semibold text-navy">Stoa</div>
      </header>

      <div className="grid grid-cols-6 gap-2 text-[12px]">
        <Stat label="Agent candidates" value={s.agents} />
        <Stat label="With financial or write authority" value={s.authorityAgents} />
        <Stat label="Unreviewed high-impact actions" value={s.unreviewedHighImpact} />
        <Stat label="Declared vs scanned contradictions" value={s.contradictions} />
        <Stat label="Open findings" value={`${activeTotal} (${RISK_LEVELS.map((l) => `${levels[l]} ${RISK_LABEL[l].toLowerCase()}`).join(", ")})`} />
        <Stat label="Changes since baseline" value={s.drift ? s.drift.changed + s.drift.added + s.drift.removed : "–"} />
      </div>

      <p className="text-[12.5px] mt-3 mb-1">
        {elevated.length ? <><strong>{elevated.length}</strong> {elevated.length === 1 ? "agent carries" : "agents carry"} elevated exposure: {elevated.map(({ agent, entries }) => `${agentLabel(agent)} (${entries.map((e) => e.id).join(", ")})`).join("; ")}.</> : "No agent carries elevated exposure in this scan."}
        {" "}Exposure is what the code makes possible, not what has happened.
      </p>

      <table className="w-full text-[11.5px] border-collapse mt-2">
        <thead>
          <tr className="border-b border-line text-left">
            <th className="py-1 pr-2">Category</th><th className="py-1 pr-2">Dimension</th><th className="py-1 pr-2">Exposure</th><th className="py-1 pr-2">Confidence</th><th className="py-1 pr-2">Findings</th><th className="py-1">Agents elevated / moderate</th>
          </tr>
        </thead>
        <tbody>
          {groups.flatMap((g) => g.cells.map((c, i) => (
            <tr key={c.dimension.id} className="border-b border-line/60">
              <td className="py-0.5 pr-2 caption">{i === 0 ? `${g.id} · ${g.label}` : ""}</td>
              <td className="py-0.5 pr-2">{c.dimension.name}</td>
              <td className="py-0.5 pr-2"><ExposureBadge exposure={c.maxExposure} /></td>
              <td className="py-0.5 pr-2 capitalize">{c.dimension.assessability}</td>
              <td className="py-0.5 pr-2 tabular-nums">{c.findingCount}</td>
              <td className="py-0.5 tabular-nums">{c.agentsElevated} / {c.agentsModerate}</td>
            </tr>
          )))}
        </tbody>
      </table>

      <div className="grid grid-cols-2 gap-4 mt-3">
        <div>
          <h3 className="text-[13px] m-0 mb-1">Top findings</h3>
          <ol className="m-0 pl-4 text-[11.5px] flex flex-col gap-0.5">
            {risks.map(({ ref, soWhat }) => (
              <li key={ref.finding.fingerprint}>
                <SeverityBadge severity={ref.finding.severity} /> {soWhat} <span className="caption mono">{ref.finding.rule_id} · {ref.finding.path}:{ref.finding.line}</span>
              </li>
            ))}
          </ol>
        </div>
        <div>
          <h3 className="text-[13px] m-0 mb-1">Fix first</h3>
          <ol className="m-0 pl-4 text-[11.5px] flex flex-col gap-0.5">
            {fixes.length === 0 ? <li className="caption list-none">No critical or high findings.</li> : fixes.map((f) => (
              <li key={`${f.rule_id}-${f.remediation}`}>
                <strong>{f.rule_id}</strong> ({f.refs.length}): {f.remediation}{f.owners.length ? <span className="caption"> · owner {f.owners.join(", ")}</span> : null}
              </li>
            ))}
          </ol>
        </div>
      </div>

      <p className="caption text-[10.5px] mt-3 mb-0">Stoa reports candidates and evidence, not certainties. A "control not observed" prompt is a review nudge, not a proven vulnerability. Framework labels ({framework === "owasp" ? "OWASP LLM Top 10 (2025)" : framework === "eu" ? "EU AI Act" : "NIST AI RMF"}) never change a score. Stoa prepares evidence; carriers price and issue.</p>
    </section>
  );
}

function Stat({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="border border-line rounded p-1.5">
      <div className="caption text-[10px] uppercase tracking-wide leading-tight">{label}</div>
      <div className="text-[17px] font-semibold text-navy leading-none mt-1">{value}</div>
    </div>
  );
}
