import type { ReactNode } from "react";
import { FRAMEWORKS, useApp } from "../app/context";
import { buildHash, type ScreenId } from "../app/router";
import { activeFindings, formatDate } from "../data/selectors";
import { printAs } from "../app/print";
import { Logo } from "./Logo";
import { PrintSummary } from "./PrintSummary";

type NavItem = { id: string; label: string; href: string; screens: ScreenId[]; count?: number };

export function Shell({ screen, children }: { screen: ScreenId; children: ReactNode }) {
  const { envelope, framework, setFramework } = useApp();
  const r = envelope.registry;
  const head = r.repository.head_commit;
  const findingCount = activeFindings(r).length;
  const declared = r.agents.filter((a) => a.declared).length;
  const driftCount = envelope.diff ? envelope.diff.summary.agents_changed + envelope.diff.summary.agents_added + envelope.diff.summary.agents_removed : 0;

  const groups: { label: string; items: NavItem[] }[] = [
    {
      label: "AI estate",
      items: [
        { id: "overview", label: "Overview", href: buildHash("overview"), screens: ["overview"] },
        { id: "inventory", label: "AI Inventory", href: buildHash("inventory"), screens: ["inventory"], count: r.agents.length },
        { id: "scope", label: "Declared Scope", href: buildHash("scope"), screens: ["scope"], count: declared },
      ],
    },
    {
      label: "Risk model",
      items: [
        { id: "risk", label: "Risk Dashboard", href: buildHash("findings"), screens: ["findings", "drift", "register"], count: findingCount + driftCount },
        { id: "controls", label: "Controls & Safeguards", href: buildHash("controls"), screens: ["controls"] },
        { id: "loss", label: "Estimated Financial Loss", href: buildHash("loss"), screens: ["loss"] },
        { id: "insurance", label: "AI Risk Insurance", href: buildHash("evidence"), screens: ["evidence"] },
      ],
    },
  ];

  return (
    <div className="min-h-screen flex flex-col md:flex-row bg-paper">
      <nav aria-label="Screens" className="no-print md:w-[240px] md:min-h-screen md:sticky md:top-0 md:self-start flex md:flex-col border-b md:border-b-0 md:border-r border-line bg-paper">
        <div className="px-5 pt-5 pb-3 hidden md:block">
          <a href={buildHash("overview")} className="inline-block text-navy" aria-label="Stoa">
            <Logo height={34} />
          </a>
        </div>
        <div className="flex md:flex-col gap-1 md:gap-4 overflow-x-auto w-full px-2 md:px-3 py-2">
          {groups.map((group) => (
            <div key={group.label} className="flex md:flex-col gap-1 shrink-0">
              <div className="hidden md:block px-3 pt-1 pb-1 text-[10.5px] uppercase tracking-[0.14em] text-ink-muted font-semibold">{group.label}</div>
              <ul className="m-0 p-0 list-none flex md:flex-col gap-0.5">
                {group.items.map((item) => {
                  const active = item.screens.includes(screen);
                  return (
                    <li key={item.id}>
                      <a
                        href={item.href}
                        aria-current={active ? "page" : undefined}
                        className={`flex items-center justify-between gap-2 rounded-md px-3 py-2 text-[14px] no-underline whitespace-nowrap ${active ? "bg-gold-100 text-navy font-medium shadow-[inset_2px_0_0_0_var(--color-gold)]" : "text-ink hover:bg-panel"}`}
                      >
                        <span>{item.label}</span>
                        {item.count !== undefined ? <span className={`text-[11px] tabular-nums rounded-full px-1.5 py-0.5 ${active ? "bg-gold/20 text-navy" : "bg-panel text-ink-muted border border-line"}`}>{item.count}</span> : null}
                      </a>
                    </li>
                  );
                })}
              </ul>
            </div>
          ))}
        </div>
        <div className="mt-auto px-5 py-3 text-[11px] text-ink-muted hidden md:block">Generated by Stoa {envelope.generator.version}</div>
      </nav>

      <div className="flex-1 min-w-0">
        <header className="bg-paper px-5 pt-4 pb-2 flex flex-wrap items-center gap-x-5 gap-y-2">
          <div className="md:hidden text-navy">
            <Logo height={26} />
          </div>
          <div className="min-w-0">
            <div className="font-serif text-[18px] text-navy leading-tight truncate">{r.repository.name}</div>
            <div className="caption">
              {r.repository.git_ref ? <span className="mono">{r.repository.git_ref}</span> : "no git ref"}
              {" · "}
              {head ? `committed ${formatDate(head.date)}` : "commit date unavailable"}
              {" · "}
              {r.summary.files_scanned} files scanned
            </div>
          </div>
          <div className="ml-auto flex items-center gap-3 no-print">
            <label className="caption flex items-center gap-2">
              Framework
              <select value={framework} onChange={(e) => setFramework(e.target.value as typeof framework)} className="rounded-md border border-line bg-panel px-2 py-1.5 text-[13px] text-ink" aria-label="Framework used for labels">
                {FRAMEWORKS.map((f) => (
                  <option key={f.id} value={f.id}>
                    {f.label}
                  </option>
                ))}
              </select>
            </label>
            <button type="button" onClick={() => printAs("summary")} className="rounded-md border border-navy bg-navy text-white px-3 py-1.5 text-[13px] hover:bg-navy-700">
              Print summary
            </button>
          </div>
        </header>
        <main className="px-5 pb-6 pt-2 max-w-[1400px]">
          <div className="screen-content">{children}</div>
          <PrintSummary />
        </main>
      </div>
    </div>
  );
}
