import type { ReactNode } from "react";
import { useApp } from "../app/context";
import { buildHash, type ScreenId } from "../app/router";
import { uniqueAgents } from "../data/agents";
import { activeFindings, countByLevel } from "../data/selectors";
import { Icon, type IconName } from "./Icons";
import { Logo } from "./Logo";
import { ScanSourceBanner } from "./OpenScan";
import { PrintSummary } from "./PrintSummary";
import { UserMenu } from "./UserMenu";

type NavItem = { id: string; label: string; href: string; screens: ScreenId[]; count?: number; alert?: string; icon: IconName };
type NavGroup = { label: string; showLabel: boolean; items: NavItem[] };

export function Shell({ screen, children }: { screen: ScreenId; children: ReactNode }) {
  const { envelope } = useApp();
  const r = envelope.registry;
  const high = countByLevel(activeFindings(envelope)).high;
  // The applicant's company from the setup details, else a name derived from the repository.
  const company = envelope.assessment.identity.company.trim() || r.repository.name;

  const groups: NavGroup[] = [
    {
      label: "Screens",
      showLabel: false,
      items: [
        { id: "overview", label: "Overview", href: buildHash("overview"), screens: ["overview"], icon: "overview" },
        { id: "inventory", label: "Agent Inventory", href: buildHash("inventory"), screens: ["inventory"], count: uniqueAgents(envelope).length, icon: "inventory" },
        // Declared Scope stays reachable at #/scope but is hidden from the sidebar for now.
        // The badge is the number that needs someone: high-severity findings, not the size of the list.
        { id: "risk", label: "Findings", href: buildHash("findings"), screens: ["findings", "drift", "register"], alert: high ? `${high} high` : undefined, icon: "risk" },
        { id: "controls", label: "Controls & Safeguards", href: buildHash("controls"), screens: ["controls"], icon: "controls" },
        { id: "loss", label: "Financial Exposure", href: buildHash("loss"), screens: ["loss"], icon: "loss" },
        { id: "insurance", label: "AI Risk Insurance", href: buildHash("evidence"), screens: ["evidence"], icon: "insurance" },
      ],
    },
  ];

  return (
    <div className="min-h-screen flex flex-col md:flex-row bg-paper">
      <nav aria-label="Screens" className="no-print md:w-[236px] md:min-h-screen md:sticky md:top-0 md:self-start flex md:flex-col border-b md:border-b-0 md:border-r border-line bg-paper">
        <div className="px-5 pt-5 pb-4 hidden md:block">
          <a href={buildHash("overview")} className="inline-block text-navy" aria-label="Stoa">
            <Logo height={30} />
          </a>
        </div>
        <div className="flex md:flex-col gap-1 md:gap-5 overflow-x-auto w-full px-2 md:px-3 py-2">
          {groups.map((group) => (
            <div key={group.label} className="flex md:flex-col gap-1 shrink-0">
              {group.showLabel ? <div className="eyebrow hidden md:block px-3 pb-1.5">{group.label}</div> : null}
              <ul className="m-0 p-0 list-none flex md:flex-col gap-px">
                {group.items.map((item) => {
                  const active = item.screens.includes(screen);
                  const Glyph = Icon[item.icon];
                  return (
                    <li key={item.id}>
                      <a
                        href={item.href}
                        aria-current={active ? "page" : undefined}
                        className={`relative flex items-center gap-2.5 rounded-md px-3 py-[7px] text-[13.5px] no-underline whitespace-nowrap ${active ? "bg-panel text-navy font-medium border border-line" : "text-ink-soft hover:text-navy hover:bg-panel/70 border border-transparent"}`}
                      >
                        {active ? <span aria-hidden="true" className="absolute left-0 top-1.5 bottom-1.5 w-[2px] rounded-full bg-gold" /> : null}
                        <span className={active ? "text-gold" : "text-ink-muted"}><Glyph /></span>
                        <span className="flex-1">{item.label}</span>
                        {item.count !== undefined ? <span className="text-[11.5px] tabular-nums text-ink-muted">{item.count}</span> : null}
                        {item.alert ? <span className="chip chip-high text-[10.5px] py-0">{item.alert}</span> : null}
                      </a>
                    </li>
                  );
                })}
              </ul>
            </div>
          ))}
        </div>
        <div className="mt-auto px-5 py-4 text-[11px] text-ink-muted hidden md:block border-t border-line">Generated by Stoa {envelope.generator.version}</div>
      </nav>

      <div className="flex-1 min-w-0">
        <header className="px-6 pt-4 pb-3 border-b border-line bg-paper flex flex-wrap items-center gap-x-5 gap-y-2">
          <div className="md:hidden text-navy">
            <Logo height={24} />
          </div>
          <div className="min-w-0 text-[15px] font-semibold text-navy leading-tight truncate" title={r.repository.name} data-testid="company">{company}</div>
          <div className="ml-auto flex items-center gap-2 no-print">
            <UserMenu />
          </div>
        </header>
        <ScanSourceBanner />
        <main className="px-6 pb-8 pt-5 max-w-[1360px]">
          <div className="screen-content">{children}</div>
          <PrintSummary />
        </main>
      </div>
    </div>
  );
}
