import { useEffect, useState } from "react";
import type { DataProvider } from "../data/provider";
import type { Envelope } from "../data/types";
import type { SchemaProblem } from "../data/schema";

type State = { status: "loading" } | { status: "ready"; envelope: Envelope } | { status: "problem"; problem: SchemaProblem };

/** Shell placeholder (M1). Screens arrive in M3 onward. */
export function App({ provider }: { provider: DataProvider }) {
  const [state, setState] = useState<State>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;
    provider.load().then((result) => {
      if (cancelled) return;
      setState("envelope" in result ? { status: "ready", envelope: result.envelope } : { status: "problem", problem: result.problem });
    });
    return () => {
      cancelled = true;
    };
  }, [provider]);

  if (state.status === "loading") return <main className="p-8">Loading scan data…</main>;
  if (state.status === "problem") {
    return (
      <main className="p-8 max-w-xl">
        <h1 className="text-xl font-semibold">This dashboard cannot read its data</h1>
        <p className="mt-2">{state.problem.message}</p>
        <p className="mt-2 text-sm">
          Found: {state.problem.found ?? "nothing"}. Expected: {state.problem.expected}. Regenerate the file with a matching Stoa release.
        </p>
      </main>
    );
  }
  const r = state.envelope.registry;
  return (
    <main className="p-8">
      <h1 className="text-xl font-semibold">{r.repository.name}</h1>
      <p className="mt-2 text-sm">
        {r.summary.agent_candidates} agent candidates · schema {r.schema_version} · generated by Stoa {state.envelope.generator.version}
      </p>
    </main>
  );
}
