import { defineConfig } from "@playwright/test";

// Every test opens a generated dashboard over file:// and must observe zero
// network requests. Dashboards are generated by e2e/global-setup.ts through
// the real `stoa dashboard` command (STOA_BIN, default `stoa` on PATH).
export default defineConfig({
  testDir: "e2e",
  globalSetup: "./e2e/global-setup.ts",
  fullyParallel: true,
  reporter: "list",
  timeout: 60_000,
  use: {
    headless: true,
    trace: "retain-on-failure",
  },
  projects: [{ name: "chromium", use: { browserName: "chromium" } }],
});
